# Generated by Django 2.2.3 on 2019-08-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
