# Generated by Django 2.2.3 on 2019-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swo_app', '0002_auto_20190806_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
